# Test

## test

### 1101

#### $dot

In [1]:
import tensorflow as tf
import numpy as np

In [30]:
x = np.arange(1,4).reshape(1,3)
x

array([[1, 2, 3]])

In [31]:
y = np.arange(1,10).reshape(3,3)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
yT = y.T
yT

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Mark
CQO

In [34]:
np.dot(x,y)

array([[30, 36, 42]])

In [33]:
np.dot(x,yT)

array([[14, 32, 50]])